### ISSUE TITLE
initCycleTLS is not a function

### ISSUE THREAD

**Issue by mrchessmaster11** [Danny-Dasilva/CycleTLS#26] opened 2021-06-02 02:44 UTC
Hi!
Looking for some help,
Using this from the example:

```
const initCycleTLS = require('cycletls');
// Typescript: import initCycleTLS from 'cycletls';

(async () => {
  const cycleTLS = await initCycleTLS();

    const response = cycleTLS('https://ja3er.com/json', {
      body: '',
      ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
      userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
      proxy: 'http://username:password@hostname.com:443'
    }, 'get');

    response.then((out) => {
      console.log(out)
    })
	
    cycleTLS.exit()

})();
```

We always get initCycleTLS is not a function, all dependencies are installed, do you know why this could be happening?

Thank you for your time,
Best,

**Comment by Danny-Dasilva** [comment] 2021-06-02 03:34
Hey, my [bug report template](https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose) goes through most of this but I need some additional info to provide support.

Please let me know your node/golang/operating system version as well as steps to reproduce. 

The more info you give the better e.g. are you running this as a typescript or js file. This repo actually has extensive [tests](https://github.com.cnpmjs.org/Danny-Dasilva/CycleTLS/actions) so there should be full coverage on Mac/windows/linux as long as installation was done correctly.

Best solution I can give right now is to delete your `node_modules` folder and reinstall

**Comment by mrchessmaster11** [comment] 2021-06-02 19:01
Tried reinstalling my node_modules, still can't recognize initCycleTLS. Currently running node v14.17.0, not sure if I even have go installed on my machine, however we were able to recognize the MyTLS package, so I don't think the golang is an issue. Also running windows 10 pro. Here is the code we are running:
(async () => {
        const cycleTLS = await initCycleTLS();
      
        const response = cycleTLS('--------', {
          body: qs.stringify(this.payload),
          headers: { 'custom-header': 'custom-value', },
          ja3: '771,255-49195-49199-49196-49200-49171-49172-156-157-47-53,0-10-11-13,23-24,0',
          //ja3: '771,60-47-61-53-10-49191-49171-49172-49195-49187-49196-49188-49161-49162-64-50-106-56-19,0-5-10-11-13-35-16-13172-23-65281,23-24,0'
          //ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28,,',
          //ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
        }, 'POST');

        response.then((out) => {
          console.log(out)
        })
      })();


I'll be obviously using an actual URL, actual headers, and a proxy as well.

**Comment by Danny-Dasilva** [comment] 2021-06-02 22:04
Cool, fantastic catch. It appears there was a TS export issue. Expect a hotfix release shortly.

**Comment by mrchessmaster11** [comment] 2021-06-03 15:53
Beautiful it looks like your code is better than myTLS which is our current solution.

**Comment by mrchessmaster11** [comment] 2021-06-05 16:17
Hi Danny!
The new update works and the function imports correctly! Great job, we managed to send the request correctly and are wanting to switch to your code. However we just noticed a new issue; 
It seems we are experiencing some issues with the process.kill for the child process.
This is the error we get 
(node:30952) UnhandledPromiseRejectionWarning: Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:200:13)
    at AsyncFunction.exit (...\node_modules\cycletls\dist\index.js:138:29)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30952) [DEP0018] 


We are using  cycleTLS.exit() at the end of the request as you did in the simple.test.js file. 
The request format has not changed since the last time we mentioned it.

Are we doing something wrong?
Thank you again for your time.

**Comment by Danny-Dasilva** [comment] 2021-06-06 17:54
@mrchessmaster11 should be addressed by [this PR](https://github.com/Danny-Dasilva/CycleTLS/pull/29) live in[ version 0.0.11](https://www.npmjs.com/package/cycletls). Issue was caused by the way windows handles killing the Golang process. Everything should cleanly exit now. I also added a multiple URL example in the [README](https://github.com/Danny-Dasilva/CycleTLS/blob/main/README.md). Keep in mind calling `cycleTLS.exit();` will close any currently running process. There are situations where you would not want to call exit.

**Closed** 2021-07-14 17:27 UTC
