### ISSUE TITLE
Socket error when using CycleTLS

### ISSUE THREAD

**Issue by dracoDevs** [Danny-Dasilva/CycleTLS#41] opened 2021-08-24 13:09 UTC
I open and close the connection after every request as instructed in documentation but after a few requests this error is thrown:
```
2021-08-24T13:04:58.761946+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761946+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761947+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761947+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761947+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761947+00:00 app[worker.1]: 2021/08/24 13:04:58 Socket Errorwebsocket: close 1006 (abnormal closure): unexpected EOF
2021-08-24T13:04:58.761947+00:00 app[worker.1]: 
2021-08-24T13:04:58.761948+00:00 app[worker.1]:     at Socket.<anonymous> (/app/node_modules/cycletls/dist/index.js:67:33)
2021-08-24T13:04:58.761948+00:00 app[worker.1]:     at Socket.emit (node:events:394:28)
2021-08-24T13:04:58.761949+00:00 app[worker.1]:     at addChunk (node:internal/streams/readable:312:12)
2021-08-24T13:04:58.761949+00:00 app[worker.1]:     at readableAddChunk (node:internal/streams/readable:287:9)
2021-08-24T13:04:58.761949+00:00 app[worker.1]:     at Socket.Readable.push (node:internal/streams/readable:226:10)
2021-08-24T13:04:58.761950+00:00 app[worker.1]:     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

I'm sending a requesting every 10 seconds and I make sure to close the connection after every request.

**Comment by Danny-Dasilva** [comment] 2021-08-24 13:37
CycleTLS has an internal  worker queue system. You don't need to close the connection or call `cycleTLS.exit();` after each call. If you want to cleanly exit at the end you can use `Promise.all()` like in the example in the [docs](https://github.com/Danny-Dasilva/CycleTLS#multiple-requests-example-for-tsjs).

I would say for repeated requests you can just not call exit and this error should no longer appear.

**Comment by dracoDevs** [comment] 2021-08-24 13:38
> CycleTLS has an internal worker queue system. You don't need to close the connection or call `cycleTLS.exit();` after each call. If you want to cleanly exit at the end you can use `Promise.all()` like in the example in the [docs](https://github.com/Danny-Dasilva/CycleTLS#multiple-requests-example-for-tsjs).
> 
> I would say for repeated requests you can just not call exit and this error should no longer appear.

I am using CycleTLS asynchronously.

**Comment by Danny-Dasilva** [comment] 2021-08-24 13:57
Right, CycleTLS has an Asynchronous internal worker queue system. 
This means asynchronicity is actually handled on the Golang side regardless of the JS implementation. 
If you make sequential calls to CycleTLS the requests will be processed asynchronously and returned as soon as Golang processes the request. 

as an example of this 

```js
const initCycleTLS = require("cycletls");

(async () => {
    const cycleTLS = await initCycleTLS();
  
      let response = cycleTLS('http://httpbin.org/delay/2', {
        body: '',
        ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
        userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
        proxy: ''
      });

      response.then((out) => {
        console.log(out) //Will always console.log second because of the delay
      })
      response = cycleTLS('http://httpbin.org/user-agent', {
        body: '',
        ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
        userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
        proxy: ''
      });
  
      response.then((out) => {
        console.log(out) //will console.log first because the request time is faster
      })
  
  })();
```

You will notice that the `delay/2` response will always log to the console second even though it is called first. This means that CycleTLS responses are always returned as soon as they are processed regardless of the order they are called in. Unless of course they are awaited.

**Comment by dracoDevs** [comment] 2021-08-24 17:00
> Right, CycleTLS has an Asynchronous internal worker queue system.
> This means asynchronicity is actually handled on the Golang side regardless of the JS implementation.
> If you make sequential calls to CycleTLS the requests will be processed asynchronously and returned as soon as Golang processes the request.
> 
> as an example of this
> 
> ```js
> const initCycleTLS = require("cycletls");
> 
> (async () => {
>     const cycleTLS = await initCycleTLS();
>   
>       let response = cycleTLS('http://httpbin.org/delay/2', {
>         body: '',
>         ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
>         userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
>         proxy: ''
>       });
> 
>       response.then((out) => {
>         console.log(out) //Will always console.log second because of the delay
>       })
>       response = cycleTLS('http://httpbin.org/user-agent', {
>         body: '',
>         ja3: '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0',
>         userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
>         proxy: ''
>       });
>   
>       response.then((out) => {
>         console.log(out) //will console.log first because the request time is faster
>       })
>   
>   })();
> ```
> 
> You will notice that the `delay/2` response will always log to the console second even though it is called first. This means that CycleTLS responses are always returned as soon as they are processed regardless of the order they are called in. Unless of course they are awaited.

Sow hat do you think is causing this ``Socket error``?

**Comment by dracoDevs** [comment] 2021-08-24 17:03
> CycleTLS has an internal worker queue system. You don't need to close the connection or call `cycleTLS.exit();` after each call. If you want to cleanly exit at the end you can use `Promise.all()` like in the example in the [docs](https://github.com/Danny-Dasilva/CycleTLS#multiple-requests-example-for-tsjs).
> 
> I would say for repeated requests you can just not call exit and this error should no longer appear.

This did help the error occurs less but it did occur after about 45 mins of continuous calls.

**Comment by Danny-Dasilva** [comment] 2021-08-24 17:24
Got it, yeah then there's a bug, something is killing the web socket connection without cleanly exiting. If you could provide some code that reliably reproduces this I can investigate.

**Comment by dracoDevs** [comment] 2021-08-24 17:36
> Got it, yeah then there's a bug, something is killing the web socket connection without cleanly exiting internally. If you could provide some code that reliably reproduces this I can investigate.
> 
> Under the issues tab there's a template for [bug reporting](https://github.com/Danny-Dasilva/CycleTLS/issues/new/choose). If you could provide the information requested in the markdown template that could help as well.

I will upload some code shortly that accurately shows you what I am trying to accomplish but another error I get when I take away ``cycletls.exit()`` altogether is this error: ``Error: listen EADDRINUSE: address already in use :::9119``.

**Comment by Danny-Dasilva** [comment] 2021-08-24 18:12
`Error: listen EADDRINUSE: address already in use :::9119` happens because you are calling `initCycleTLS();`  multiple times (remember this is not necessary because anything passed to the first instance created will be handled by the internal Golang queue).

 if you want to do this you need to pass a different port to it e.g. `const cycleTLS = await initCycleTLS({port: 9118});` or some port other than `9119`

**Comment by dracoDevs** [comment] 2021-08-24 18:46
> `Error: listen EADDRINUSE: address already in use :::9119` happens because you are calling `initCycleTLS();` multiple times (remember this is not necessary because anything passed to the first instance created will be handled by the internal Golang queue).
> 
> if you want to do this you need to pass a different port to it e.g. `const cycleTLS = await initCycleTLS({port: 9118});` or some port other than `9119`

Thank for the support!  Great module you have here!

**Comment by dracoDevs** [comment] 2021-08-24 20:55
> `Error: listen EADDRINUSE: address already in use :::9119` happens because you are calling `initCycleTLS();` multiple times (remember this is not necessary because anything passed to the first instance created will be handled by the internal Golang queue).
> 
> if you want to do this you need to pass a different port to it e.g. `const cycleTLS = await initCycleTLS({port: 9118});` or some port other than `9119`

Now I get a new error after some time ``Error: panic: runtime error: invalid memory address or nil pointer dereference``.

**Comment by Stephen-PP** [comment] 2021-08-24 21:07
code?

**Comment by Danny-Dasilva** [comment] 2021-08-24 21:12
This may be related to this [Ja3 Token Parsing error ](https://github.com/Danny-Dasilva/CycleTLS/issues/39) but I cannot bugfix something I can't reproduce.

**Comment by Danny-Dasilva** [comment] 2021-09-16 20:52
Addressed by this [PR](https://github.com/Danny-Dasilva/CycleTLS/pull/45). Feel free to open another issue if you experience errors.

**Closed by Danny-Dasilva** 2021-09-16 20:52 UTC
