### ISSUE TITLE
 Extension {{ 17513 }} is not Supported by CycleTLS please raise an issue

### ISSUE THREAD

**Issue by belian001** [Danny-Dasilva/CycleTLS#88] opened 2022-04-27 07:26 UTC
### Description

He seems to show that the value 17513 is not supported. Can this be fixed?

### Issue Type

Feature Request

### Operating System

Windows 10

### Relevant Log Output

```shell
Extension {{ 17513 }} is not Supported by CycleTLS please raise an issue
```

**Comment by belian001** [comment] 2022-04-27 07:29
CycleTLS is a very good project, I am a fan of this project, but because it does not support modifying a specific value, so I am currently researching how to freely modify the value of openssl, but I encountered some problems

**Comment by belian001** [comment] 2022-04-27 07:40
In the ssl_cipher_list_to_bytes method in the staten_clnt.c file in openssl, put_cipher_by_char assigns the cipher suite, this method finally pushes the id member of ssl_cipher_st, and then I start to assign the id member, but the assignment is unsuccessful, the value does not appear, Weird, don't know where is the problem

**Comment by belian001** [comment] 2022-04-27 07:45
Below are my test results, I have assigned the first 5 values, but none of them appear. How to solve this?

> 
![1eb8c9b3fe2af595186afb926697489](https://user-images.githubusercontent.com/53556428/165467952-98046769-aa4d-45a7-a371-8d9571826746.png)

**Comment by Danny-Dasilva** [comment] 2022-04-27 13:24
this is a duplicate of #70, currently working on implementing this extension. I will update this when the feature is implemented.

**Comment by belian001** [comment] 2022-04-27 14:12
> 



> 这是#70的副本，目前正在实施此扩展。我会在实现该功能时更新它。

thanks, when will the fix be done

**Comment by KawaCode** [comment] 2022-05-14 16:04
Hey, i just want to say, that this is not a issue, its just wireshark reporting wrong JA3 string!

**Comment by Danny-Dasilva** [comment] 2022-05-16 10:56
Extension 17513 is now supported as of [this release](https://github.com/Danny-Dasilva/CycleTLS/pull/91). Ja3er does not properly return this extension due to it's [known issues](https://github.com/Danny-Dasilva/CycleTLS/issues/39#issuecomment-922154225). However sites like https://tls.peet.ws/api/clean and Wireshark should verify that we are returning `17513`.

**Closed by Danny-Dasilva** 2022-05-16 10:56 UTC
Labels: duplicate
