### ISSUE TITLE
Issue in Extension 34 and 41

### ISSUE THREAD

**Issue by ghost** [Danny-Dasilva/CycleTLS#96] opened 2022-05-29 23:23 UTC
CycleTLS doesn't request to any site with any valid JA3

I dont know the issue but the error is in extension number 34.

JA3 used:   **771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53-10,0-23-65281-10-11-16-5-34-51-43-13-45-28-41,29-23-24-25-256-257,0**

Edit: the errors, that i get are in extension 34 and 41.

**Comment by Danny-Dasilva** [comment] 2022-05-30 11:48
Investigating but I currently believe that this issue is a duplicate of [this](https://github.com/Danny-Dasilva/CycleTLS/issues/93). You have extension `41` which is a pre shared key in your Ja3.

**Comment by KawaCode** [comment] 2022-06-06 22:54
@Danny-Dasilva Did you find anything?

**Comment by Danny-Dasilva** [comment] 2022-06-20 10:49
Session based key resumption is a little difficult to implement. I'll get around to this eventually but it does require large effort to do.

**Comment by Danny-Dasilva** [comment] 2023-11-28 05:38
Pre Shared Key  and DelegatedCredentialsExtension are both now supported with the latest release
https://github.com/Danny-Dasilva/CycleTLS/blob/f6c898f1bb298f3d6dd7fcfdfb531d950cc587a3/cycletls/utils.go#L294-L303

**Closed by Danny-Dasilva** 2023-11-28 05:38 UTC
Labels: ✨ Enhancement, help wanted
